### ISSUE TITLE
todo list for the 4.0.0 version

### ISSUE THREAD

**Issue by CrackAndDie** [CrackAndDie/shufflecad-4#1]
## The things that should be done before releasing the 4.0.0 version:
- [x] Chart controls
- [x] Slider control
- [x] Merging variable lists
- [x] Not removing variables that are on front panel
- [x] Adding time views of the rest of the communication threads
- [x] Making buttons on the front panel work
- [x] Adding right click menu to each of the front variables
- [x] Adding "open chart window" feature to the chart control
- [x] Adding auto connect button near to the run button
- [x] Adding show password button near to the password field
- [x] Adding grid to the front canvas and set confines to it
- [x] Make settings work
- [x] Removing save button everywhere
- [x] Adding usage of the top label to some important actions
- [x] Adding logo to the top of the main window
