### ISSUE TITLE
todo list of features that should be done

### ISSUE THREAD

**Issue by CrackAndDie** [CrackAndDie/shufflecad-4#2]
- [x] Saving slider min and max values
- [x] Save as *.txt* logger page
- [x] Change this cringe orange buttons
- [x] Save camera image as file
- [x] Copy camera image to buffer
- [x] Sorting variables
- [x] Language switcher
